; ssgfunc.asm

extrn	ssg_ecm					:near
extrn	ssg_note_off			:near
extrn	ssg_note_on				:near
extrn	ssg_poly_keypress		:near
extrn	ssg_bank_select			:near
extrn	ssg_modulation			:near
extrn	ssg_pol_time			:near
extrn	ssg_data_entry			:near
extrn	ssg_volume				:near
extrn	ssg_panpot				:near
extrn	ssg_expression			:near
extrn	ssg_hold1				:near
extrn	ssg_poltament			:near
extrn	ssg_sostenuto			:near
extrn	ssg_soft				:near
extrn	ssg_pol_ctrl			:near
extrn	ssg_effect1				:near
extrn	ssg_effect3				:near
extrn	ssg_nrpn				:near
extrn	ssg_rpn					:near
extrn	ssg_prog_chg			:near
extrn	ssg_ch_presser			:near
extrn	ssg_pitchbend			:near
extrn	ssg_all_soundoff		:near
extrn	ssg_all_resetctrler		:near
extrn	ssg_all_noteoff			:near
extrn	ssg_omni_off			:near
extrn	ssg_omni_on				:near
extrn	ssg_mono				:near
extrn	ssg_poly				:near
extrn	ssg_active_sence		:near
extrn	ssg_exclusive			:near
extrn	ssg_vibrato				:near
extrn	ssg_master_volume		:near
