#include	stdio.mac
#include	ym2203.mac
.object _main
T1 = SSG(0);
{
	T1	t120l8o5v15;
	T1	@ecm[(SSG_DRVIDNUM),(SSG_DRVTYPE),0x00,w0,0,
		w10,w5000,0,
		0,5,-1,5,-1,5,-1,5,-1,5,-1,5,0x80];
	T1	@0m40[2 c1d1e1];
}
