; beepfunc.asm

extrn	beep_note_off			:near
extrn	beep_note_on			:near
extrn	beep_poly_keypress		:near
extrn	beep_bank_select		:near
extrn	beep_modulation			:near
extrn	beep_pol_time			:near
extrn	beep_data_entry			:near
extrn	beep_volume				:near
extrn	beep_panpot				:near
extrn	beep_expression			:near
extrn	beep_hold1				:near
extrn	beep_poltament			:near
extrn	beep_sostenuto			:near
extrn	beep_soft				:near
extrn	beep_pol_ctrl			:near
extrn	beep_effect1			:near
extrn	beep_effect3			:near
extrn	beep_nrpn				:near
extrn	beep_rpn				:near
extrn	beep_prog_chg			:near
extrn	beep_ch_presser			:near
extrn	beep_pitchbend			:near
extrn	beep_all_soundoff		:near
extrn	beep_all_resetctrler	:near
extrn	beep_all_noteoff		:near
extrn	beep_omni_off			:near
extrn	beep_omni_on			:near
extrn	beep_mono				:near
extrn	beep_poly				:near
extrn	beep_active_sence		:near
extrn	beep_exclusive			:near
extrn	beep_vibrato			:near
extrn	beep_master_volume		:near

