# 
# beep.xdv makefile		DDNê—p beep‰¹Œ¹‘Î‰ƒhƒ‰ƒCƒo[ beep.xdv
#
# copyright (c) 1993 by ABA / Interfair all rights reserved.
# 
# makefile copyright (c) 1993 by ABA  all rights reserved.
#
!include	"..\sysdir.inc"

#
# project files 
#
objs =	beepfunc.obj
exec	= beep
base	= beep

#
# object and executable file be made.
#
.asm.obj:
	@echo [43m -- Compiling : $< -- [m
	tasm /ml $<
.c.obj:
	@echo [43m -- Compiling : $< -- [m
	tcc -mc -c $<

$(exec).xdv : $(base).obj $(tmp)$(exec).lib
	@echo [42m -- Making $(exec)... -- [m
	tlink /t /x $(base).obj ,$(exec).xdv ,,$(tmp)$(exec)
	@copy $(exec).xdv $(junktest):
	@echo [41m -- Complete -- [m
#
# library be made.
#
$(tmp)$(exec).lib : $(objs)
	@echo [46m -- Making $(exec).lib public library -- [m
	@del $(tmp)$(exec).lib
	tlib $(tmp)$(exec).lib @object

#
# program object be made by.
#
beep.obj	:	beep.asm	..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					beep.inc            \
					beepfunc.inc        

beepfunc.obj	:	beepfunc.asm	..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					beep.inc            \
					beepfunc.inc        

