#include ym2203.mac
.object _main
SOUND = *SOUND;
MUSIC = OPN(0);
{
	SOUND	(opnsound(0,3,52,40,3500,
		 18, 20,  0,  1,  3, 27,  0,  4, -1, 0,
		 12, 20,  0,  6,  1,  5,  0,  4, -1, 0,
		 28, 18,  0,  1,  4, 29,  0,  6,  1, 0,
		 28, 10,  0,  6,  5,  0,  0,  4, -1, 0));
	MUSIC	t127 @3 @v95 l8 o5 x127 @e127 m60;
	MUSIC	a4b4
			>c<bga&a2& a1
			>c<b>cd4/50<g/80g4& g2./90r4;
}
