; opl2func.asm

extrn	opl2_ecm				:near
extrn	opl2_note_off			:near
extrn	opl2_note_on			:near
extrn	opl2_poly_keypress		:near
extrn	opl2_bank_select		:near
extrn	opl2_modulation			:near
extrn	opl2_pol_time			:near
extrn	opl2_data_entry			:near
extrn	opl2_volume				:near
extrn	opl2_panpot				:near
extrn	opl2_expression			:near
extrn	opl2_hold1				:near
extrn	opl2_poltament			:near
extrn	opl2_sostenuto			:near
extrn	opl2_soft				:near
extrn	opl2_pol_ctrl			:near
extrn	opl2_effect1			:near
extrn	opl2_effect3			:near
extrn	opl2_nrpn				:near
extrn	opl2_rpn				:near
extrn	opl2_prog_chg			:near
extrn	opl2_ch_presser			:near
extrn	opl2_pitchbend			:near
extrn	opl2_all_soundoff		:near
extrn	opl2_all_resetctrler	:near
extrn	opl2_all_noteoff		:near
extrn	opl2_omni_off			:near
extrn	opl2_omni_on			:near
extrn	opl2_mono				:near
extrn	opl2_poly				:near
extrn	opl2_active_sence		:near
extrn	opl2_exclusive			:near
extrn	opl2_vibrato			:near
extrn	opl2_master_volume		:near
