# 
# sbmidi.XDV makefile	DDNê—p sbmidi-GS‰¹Œ¹‘Î‰ƒhƒ‰ƒCƒo[ sbmidi.XDV
#
# copyright (c) 1993 by ABA / Interfair all rights reserved.
# 
# makefile copyright (c) 1993 by ABA  all rights reserved.
#
!include	"..\sysdir.inc"

#
# project files 
#
objs =	sbmdterm.obj	sbmdfunc.obj
exec	= sbmidi
base	= sbmidi

#
# object and executable file be made.
#
.asm.obj:
	@echo [43m -- Compiling : $< -- [m
	tasm /ml $<
.c.obj:
	@echo [43m -- Compiling : $< -- [m
	tcc -mc -c $<

$(exec).xdv : $(base).obj $(tmp)$(exec).lib
	@echo [42m -- Making $(exec)... -- [m
	tlink /t /x $(base).obj ,$(exec).xdv ,,$(tmp)$(exec)
	@copy $(exec).xdv $(junktest):
	@echo [41m -- Complete -- [m
#
# library be made.
#
$(tmp)$(exec).lib : $(objs)
	@echo [46m -- Making $(exec).lib public library -- [m
	@del $(tmp)$(exec).lib
	tlib $(tmp)$(exec).lib @object

#
# program object be made by.
#
sbmidi.obj	:	sbmidi.asm	..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					sbmidi.inc            \
					sbmdterm.inc        \
					sbmdfunc.inc        

sbmdterm.obj	:	sbmdterm.asm	..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					sbmidi.inc            \
					sbmdterm.inc        \
					sbmdfunc.inc        

sbmdfunc.obj	:	sbmdfunc.asm	..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					sbmidi.inc            \
					sbmdterm.inc        \
					sbmdfunc.inc        

