; midifunc.asm

extrn	midi_note_off			:near
extrn	midi_note_on			:near
extrn	midi_poly_keypress		:near
extrn	midi_bank_select		:near
extrn	midi_modulation			:near
extrn	midi_pol_time			:near
extrn	midi_data_entry			:near
extrn	midi_volume				:near
extrn	midi_panpot				:near
extrn	midi_expression			:near
extrn	midi_hold1				:near
extrn	midi_poltament			:near
extrn	midi_sostenuto			:near
extrn	midi_soft				:near
extrn	midi_pol_ctrl			:near
extrn	midi_effect1			:near
extrn	midi_effect3			:near
extrn	midi_nrpn				:near
extrn	midi_rpn				:near
extrn	midi_prog_chg			:near
extrn	midi_ch_presser			:near
extrn	midi_pitchbend			:near
extrn	midi_all_soundoff		:near
extrn	midi_all_resetctrler	:near
extrn	midi_all_noteoff		:near
extrn	midi_omni_off			:near
extrn	midi_omni_on			:near
extrn	midi_mono				:near
extrn	midi_poly				:near
extrn	midi_active_sence		:near
extrn	midi_exclusive			:near
extrn	midi_vibrato			:near
extrn	midi_master_volume		:near

