# 
# mld.exe makefile
#
# copyright (c) 1993 by ABA / Interfair all rights reserved.
# 
# makefile copyright (c) 1993 by ABA  all rights reserved.
#
!include	"..\sysdir.inc"

#
# project files 
#
objs =	mld.obj		mld_func.obj	mld_opt.obj	\
	mld_lfil.obj
exec	= mld
#debugobj= $(lib)\c0t.obj
#debuglib= $(lib)\cs.lib

#
# object and executable file be made.
#
.asm.obj:
	@echo [43m -- Compiling : $< -- [m
	tasm /mx /m $<
.c.obj:
	@echo [43m -- Compiling : $< -- [m
	tcc -mc -c $<

$(exec).exe : $(tmp)$(exec).lib
	@echo [42m -- Making $(exec)... -- [m
	tlink $(lib)\c0c.obj, $(exec).exe,, $(tmp)$(exec) $(lib)\tls $(lib)\mfxddn $(lib)\cc 
	@copy $(exec).exe $(junktest):
	@echo [41m -- Complete -- [m
#
# library be made.
#
$(tmp)$(exec).lib : $(objs)
	@echo [46m -- Making $(exec).lib public library -- [m
	@del $(tmp)$(exec).lib
	tlib $(tmp)$(exec).lib @object

#
# program object be made by.
#
mld.obj		:	mld.c

mld_func.obj	:	mld_func.asm

mld_opt.obj	:	mld_opt.c

mld_lfil.obj	:	mld_lfil.c

