char *soundlist[256] = 
{
	"Piano1",
	"Piano2",
	"Piano3",
	"Honky-tonk",
	"E.Piano1",
	"E.Piano2",
	"Harpsichord",
	"Clav.",
	"Celesta",
	"Glockenspiel",
	"Music Box",
	"Vibraphone",
	"Marinba",
	"Xylophone",
	"Tubular-bell",
	"Santur",
	"Organ1",
	"Organ2",
	"Organ3",
	"Chunch Org.1",
	"Reed Organ",
	"Accordion Fr",
	"Harmonica",
	"Bandneon",
	"Nylon-Str.Gt",
	"Steel-Gt",
	"Jazz-Gt",
	"Clean-Gt",
	"Muted-Gt",
	"OverdriveGt",
	"DistortionGt",
	"Gt.Harmonics",
	"Acoustic Bs.",
	"Fingerd Bs.",
	"Picked Bs.",
	"Fretless Bs.",
	"Slap Bass1",
	"Slap Bass2",
	"Synth Bass1",
	"Synth Bass2",
	"Violin",
	"Viola",
	"Cello",
	"Contrabass",
	"Tremolo Str",
	"PizzicatoStr",
	"Harp",
	"Timpani",
	"Strings",
	"Slow Strings",
	"Syn.Strings1",
	"Syn.Strings2",
	"Choir Aahs",
	"Voice Oohs",
	"SynVox",
	"OrchestraHit",
	"Trumpet",
	"Trombone",
	"Tuba",
	"MutedTrumpet",
	"French Horn",
	"Brass1",
	"Synth Brass1",
	"Synth Brass2",
	"Soprano Sax",
	"Alto Sax",
	"Tenor Sax",
	"Baritone Sax",
	"Oboe",
	"English Horn",
	"Bassoon",
	"Clarinet",
	"Piccolo",
	"Flute",
	"Recorder",
	"Pan Flute",
	"Bottle Blow",
	"Shakuhachi",
	"Whistle",
	"Ocarina",
	"Square Wave",
	"Saw Wave",
	"Syn.Calliop",
	"Chiffer Lead",
	"Charang",
	"Solo Vox",
	"5th Saw Wave",
	"Bass & Lead",
	"Fantasia",
	"Warm Pad",
	"Polysynth",
	"Space Voice",
	"Bowed Grass",
	"Metal Pad",
	"Halo Pad",
	"Sweep Pad",
	"Ice Rain",
	"Soundtrack",
	"Crystal",
	"Atmosphere",
	"Brightness",
	"Goblin",
	"Echo Drops",
	"Star Theme",
	"Sitar",
	"Banjo",
	"Shamisen",
	"koto",
	"Kalimba",
	"Bag Pipe",
	"Fiddle",
	"Shannai",
	"Tinkle Bell",
	"Agogo",
	"Steel Drums",
	"Woodblock",
	"Taiko",
	"Melo Tom1",
	"Synth Drum",
	"Reverse Cym.",
	"Gt.FretNoise",
	"Breath Noise",
	"Seashore",
	"Bird",
	"Telephone",
	"Helicopter",
	"Applause",
	"Gun Shot",

	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -",
	"- No Inst -"
};
