# 
# oplsound.EXE makefile
#
# copyright (c) 1993 by ABA / Interfair all rights reserved.
# 
# makefile copyright (c) 1993 by ABA  all rights reserved.
#
!include	"..\sysdir.inc"

#
# project
#
objs =	oplsound.obj
exec	= oplsound
#debugobj= $(lib)\c0t.obj
#debuglib= $(lib)\cs.lib

#
# object and executable file be made.
#
.asm.obj:
	@echo [43m -- Compiling : $< -- [m
	tasm /ml /m $<
.c.obj:
	@echo [43m -- Compiling : $< -- [m
	tcc -mc -c $<

$(exec).exe : $(tmp)$(exec).lib $(exec).fld
	@echo [42m -- Making $(exec)... -- [m
	tlink /x $(lib)\c0c.obj , $(exec).exe , , $(tmp)$(exec) $(lib)\tls $(lib)\masterc $(lib)\cc
	filelink e $(exec).exe $(exec).fld
	@copy $(exec).exe $(junktest):
	@echo [41m -- Complete -- [m
#
# library be made.
#
$(tmp)$(exec).lib : $(objs) $(lib)\mfxddn.lib
	@echo [46m -- Making $(exec).lib public library -- [m
	@del $(tmp)$(exec).lib
	tlib $(tmp)$(exec).lib @object

#
# program object be made by.
#
oplsound.obj		:	oplsound.c	oplsound.h	sound.h

oplsound.fld		:	b:\mfxddn\test\sb98.xdv b:\mfxddn\test\midi.xdv
	@del oplsound.fld
	filelink a oplsound.fld b:\mfxddn\test\sb98.xdv
	filelink a oplsound.fld b:\mfxddn\test\midi.xdv
