# 
# opn.xdv makefile		DDNêÍóp OPNÉhÉâÉCÉoÅ[ opn.xdv
#
# copyright (c) 1994 by ABA / Interfair all rights reserved.
# 
# makefile copyright (c) 1994 by ABA  all rights reserved.
#
!include	"..\sysdir.inc"

#
# project files 
#
objs =	opnterm.obj	opninit.obj	opnfunc.obj	opnsound.obj	\
	opnvol.obj
exec	= opn
base	= opn

#
# object and executable file be made.
#
.asm.obj:
	@echo [43m -- Compiling : $< -- [m
	tasm /ml $<
.c.obj:
	@echo [43m -- Compiling : $< -- [m
	tcc -mc -c $<

$(exec).xdv : $(base).obj $(tmp)$(exec).lib
	@echo [42m -- Making $(exec)... -- [m
	tlink /t /x $(base).obj ,$(exec).xdv ,,$(tmp)$(exec)
	@copy $(exec).xdv $(junktest):
	@echo [41m -- Complete -- [m
#
# library be made.
#
$(tmp)$(exec).lib : $(objs)
	@echo [46m -- Making $(exec).lib public library -- [m
	@del $(tmp)$(exec).lib
	tlib $(tmp)$(exec).lib @object

#
# program object be made by.
#
opn.obj		:	opn.asm		..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					opn.inc            \
					opnterm.inc        \
					opnfunc.inc        
opnterm.obj	:	opnterm.asm	..\kernel\stdio.inc \
			opnfltr.inc	..\kernel\ddn.inc   \
					opn.inc            \
					opnterm.inc        \
					opnfunc.inc        
opninit.obj	:	opninit.asm	..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					opn.inc            \
					opnterm.inc        \
					opnfunc.inc        
opnfunc.obj	:	opnfunc.asm	..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					opn.inc            \
					opnterm.inc        \
					opnfreq.inc
opnsound.obj	:	opnsound.asm	..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					opn.inc            \
					opnterm.inc        \
					opndeflt.inc
opnvol.obj	:	opnvol.asm	..\kernel\stdio.inc \
					..\kernel\ddn.inc   \
					opn.inc            \
					opnterm.inc

