; opnfunc.asm

extrn	opn_ecm					:near
extrn	opn_note_off			:near
extrn	opn_note_on				:near
extrn	opn_poly_keypress		:near
extrn	opn_bank_select			:near
extrn	opn_modulation			:near
extrn	opn_pol_time			:near
extrn	opn_data_entry			:near
extrn	opn_volume				:near
extrn	opn_panpot				:near
extrn	opn_expression			:near
extrn	opn_hold1				:near
extrn	opn_poltament			:near
extrn	opn_sostenuto			:near
extrn	opn_soft				:near
extrn	opn_pol_ctrl			:near
extrn	opn_effect1				:near
extrn	opn_effect3				:near
extrn	opn_nrpn				:near
extrn	opn_rpn					:near
extrn	opn_prog_chg			:near
extrn	opn_ch_presser			:near
extrn	opn_pitchbend			:near
extrn	opn_all_soundoff		:near
extrn	opn_all_resetctrler		:near
extrn	opn_all_noteoff			:near
extrn	opn_omni_off			:near
extrn	opn_omni_on				:near
extrn	opn_mono				:near
extrn	opn_poly				:near
extrn	opn_active_sence		:near
extrn	opn_exclusive			:near
extrn	opn_vibrato				:near
extrn	opn_master_volume		:near
