#title チューリップのうた。
.object _main
MELODY=BEEP(0);
{
       MELODY   t120l4o5q90;
       MELODY   cde2 cde2;
       MELODY   gedcded2;
       MELODY   cde2 cde2;
       MELODY   gedcdec2;
       MELODY   ggegaag2;
       MELODY   eeddc1;
}
