#title チューリップのうた。
.object _main
MELODY=SSG(0);
BASS=SSG(1);
{
       MELODY   t120l4o5q90;
       MELODY   cde2 cde2;
       MELODY   gedcded2;
       MELODY   cde2 cde2;
       MELODY   gedcdec2;
       MELODY   ggegaag2;
       MELODY   eeddc1;

	BASS	l8o3
			[2
			[2 c>c<c>c<c>c<c>c<]
			g>g<g>g<g>g<g>g<:g>g<g>g<g>g<g>g<
			]
			f>f<f>f<c>c<c>c<;
}
