# 
# sabst.EXE makefile
#
# copyright (c) 1993 by ABA / Interfair all rights reserved.
# 
# makefile copyright (c) 1993 by ABA  all rights reserved.
#
!include	"..\sysdir.inc"

#
# project files 
#
objs =	sabst.obj
exec	= sabst
#debugobj= $(lib)\c0t.obj
#debuglib= $(lib)\cs.lib

#
# object and executable file be made.
#
.asm.obj:
	@echo [43m -- Compiling : $< -- [m
	tasm /sabst /m $<
.c.obj:
	@echo [43m -- Compiling : $< -- [m
	tcc -mc -c $<

$(exec).exe : $(tmp)$(exec).lib
	@echo [42m -- Making $(exec)... -- [m
	tlink $(lib)\c0c.obj , $(exec).exe ,, $(tmp)$(exec) $(lib)\tls $(lib)\mfxddn $(lib)\cc
	@copy $(exec).exe $(junktest):
	@echo [41m -- Complete -- [m
#
# library be made.
#
$(tmp)$(exec).lib : $(objs)
	@echo [46m -- Making $(exec).lib public library -- [m
	@del $(tmp)$(exec).lib
	tlib $(tmp)$(exec).lib @object

#
# program object be made by.
#
sabst.obj		:	sabst.c		sabst.h

